module.exports = (api) => {
    api.cache(true);
    return {
        presets: ['babel-preset-expo'],
        plugins: [
            'react-native-reanimated/plugin',
            'nativewind/babel',
            [
                'module-resolver',
                {
                    alias: {
                        // This needs to be mirrored in tsconfig.json
                        '@': './'
                    }
                }
            ],
            [
                'react-native-iconify/babel',
                {
                    icons: [
                        'basil:user-outline',
                        'clarity:email-line',
                        'mdi:password-outline',
                        'fa-solid:place-of-worship',
                        'arcticons:budgetbakers-wallet',
                        'icon-park-solid:tips-one',
                        'gis:map-favorite',
                        'grommet-icons:next',
                        'material-symbols:star',
                        'hugeicons:location-favourite-01',
                        'lets-icons:home',
                        'material-symbols:calendar-month',
                        'mdi:magic',
                        'iconamoon:profile-fill',
                        'material-symbols:search',
                        'material-symbols:close',
                        'lets-icons:back-light',
                        'mdi:filter',
                        'solar:calendar-linear',
                        'mi:location',
                        'weui:share-outlined',
                        'mdi:eye-outline',
                        'mdi:eye-off-outline',
                        'mdi:account',
                        'pepicons-pencil:leave',
                        'material-symbols:settings-outline',
                        'tabler:trash-off',
                        'mdi:translate',
                        'mdi:history',
                        'mdi-light:bell',
                        'carbon:password',
                        'material-symbols:help-outline',
                        'mdi-light:comment',
                        'solar:shield-line-duotone',
                        'akar-icons:file',
                        'devicon:facebook',
                        'skill-icons:instagram',
                        'mingcute:down-line',
                        'fontisto:map-marker',
                        'material-symbols:map',
                        'mdi:clock-outline',
                        'mdi:chevron-down',
                        'mdi:chevron-right',
                        'bi:three-dots',
                        'mdi:pencil',
                        'mdi:trash-can',
                        'mdi:dots-grid',
                        'mdi-light:map-marker',
                        'mdi-light:note',
                        'material-symbols-light:checklist',
                        'mdi:view-grid-outline',
                        'mdi:chevron-up',
                        'mdi:briefcase-outline',
                        'fluent:note-48-filled',
                        'mdi:map-marker-outline',
                        'mdi:magnify',
                        'mdi:pencil-outline',
                        'mdi:close',
                        'ic:baseline-plus',
                        'mdi:airplane',
                        'mdi:bed',
                        'mdi:car',
                        'mdi:silverware-fork-knife',
                        'mdi:paperclip',
                        'mdi:dots-horizontal',
                        'mdi:train',
                        'mdi:bus',
                        'mdi:ferry',
                        'mdi:ship-wheel',
                        'mdi:star',
                        'fa-solid:map-marker',
                        'mdi:currency-usd',
                        'devicon:google',
                        'mdi:map-marker',
                        'mdi:link',
                        'mdi:phone',
                        'mdi:info',
                        'mdi:clock',
                        'mdi:world',
                        'material-symbols:info',
                        'mdi:calendar-edit',
                        'mdi:magic-wand',
                        'fa-solid:route',
                        'tabler:calendar-x'
                    ]
                }
            ]
            // require.resolve('expo-router/babel')
        ]
    };
};
