export const currencies = [
    { name: 'US Dollar', code: 'USD', symbol: '$', icon: 'openmoji:flag-us-outlying-islands' },
    { name: 'Euro', code: 'EUR', symbol: '€', icon: 'openmoji:flag-european-union' },
    { name: 'British Pound', code: 'GBP', symbol: '£', icon: 'openmoji:flag-british-indian-ocean-territory' },
    { name: 'Japanese Yen', code: 'JPY', symbol: '¥', icon: 'openmoji:flag-japan' },
    { name: 'Australian Dollar', code: 'AUD', symbol: 'A$', icon: 'openmoji:flag-australia' },
    { name: 'Canadian Dollar', code: 'CAD', symbol: 'C$', icon: 'openmoji:flag-canada' },
    { name: 'Swiss Franc', code: 'CHF', symbol: 'CHF', icon: 'emojione-v1:flag-for-switzerland' },
    { name: 'Chinese Yuan', code: 'CNY', symbol: '¥', icon: 'openmoji:flag-china' },
    { name: 'Hong Kong Dollar', code: 'HKD', symbol: 'HK$', icon: 'openmoji:flag-hong-kong-sar-china' },
    { name: 'Singapore Dollar', code: 'SGD', symbol: 'S$', icon: 'openmoji:flag-singapore' },
    { name: 'South Korean Won', code: 'KRW', symbol: '₩', icon: 'openmoji:flag-south-korea' },
    { name: 'New Zealand Dollar', code: 'NZD', symbol: 'NZ$', icon: 'openmoji:flag-new-zealand' },
    { name: 'Mexican Peso', code: 'MXN', symbol: 'Mex$', icon: 'openmoji:flag-mexico' },
    { name: 'Indian Rupee', code: 'INR', symbol: '₹', icon: 'openmoji:flag-india' },
    { name: 'Brazilian Real', code: 'BRL', symbol: 'R$', icon: 'openmoji:flag-brazil' },
    { name: 'South African Rand', code: 'ZAR', symbol: 'R', icon: 'openmoji:flag-south-africa' },
    { name: 'Russian Ruble', code: 'RUB', symbol: '₽', icon: 'openmoji:flag-russia' },
    { name: 'Turkish Lira', code: 'TRY', symbol: '₺', icon: 'openmoji:flag-turkey' },
    { name: 'United Arab Emirates Dirham', code: 'AED', symbol: 'د.إ', icon: 'openmoji:flag-united-arab-emirates' },
    { name: 'Thai Baht', code: 'THB', symbol: '฿', icon: 'openmoji:flag-thailand' },
    { name: 'Indonesian Rupiah', code: 'IDR', symbol: 'Rp', icon: 'openmoji:flag-indonesia' },
    { name: 'Philippine Peso', code: 'PHP', symbol: '₱', icon: 'openmoji:flag-philippines' },
    { name: 'Vietnamese Dong', code: 'VND', symbol: '₫', icon: 'openmoji:flag-vietnam' },
    { name: 'Saudi Riyal', code: 'SAR', symbol: '﷼', icon: 'openmoji:flag-saudi-arabia' },
    { name: 'Malaysian Ringgit', code: 'MYR', symbol: 'RM', icon: 'openmoji:flag-malaysia' },
    { name: 'Colombian Peso', code: 'COP', symbol: 'COL$', icon: 'openmoji:flag-colombia' },
    { name: 'Chilean Peso', code: 'CLP', symbol: 'CLP$', icon: 'openmoji:flag-chile' },
    { name: 'Egyptian Pound', code: 'EGP', symbol: 'E£', icon: 'openmoji:flag-egypt' },
    { name: 'Nigerian Naira', code: 'NGN', symbol: '₦', icon: 'openmoji:flag-nigeria' },
    { name: 'Argentine Peso', code: 'ARS', symbol: 'ARS$', icon: 'openmoji:flag-argentina' }
];
